### ISSUE TITLE
No timeout is defined when a OAI repository is not available

### ISSUE THREAD

**Issue by andrefgomes** [DSpace/xoai#38]
XOAI will try forever to connect to a OAI repository that is not available

**Comment by mdcarreira** [comment]
For what I could assert, it gives a timeout:
```
com.lyncode.xoai.serviceprovider.exceptions.HttpException: java.net.SocketTimeoutException: Read timed out
    at com.lyncode.xoai.serviceprovider.client.HttpOAIClient.execute(HttpOAIClient.java:98)
    at com.lyncode.xoai.serviceprovider.handler.IdentifyHandler.handle(IdentifyHandler.java:38)
    at com.lyncode.xoai.serviceprovider.ServiceProvider.identify(ServiceProvider.java:45)
```
If anyone can replicate this issue please let us know.
