### ISSUE TITLE
listSets() resumptionToken causes IllegalStateException

### ISSUE THREAD

**Issue by Abdull** [DSpace/xoai#55]
I'm trying to receive the list of sets from a OAI handler. As the particular repository I'm querying has more than 100 sets, its handler provides sets in chunks of 100 with an additional `resumptionToken` element.
I use XOAI like in the following snippet:

```
        OAIClient oaiClient = new HttpOAIClient("http://www.example.com/oai/request");

         Context context = new Context()
                .withOAIClient(oaiClient);

         ServiceProvider ssoarOaiPmhEndpoint = new ServiceProvider(context);         
         Iterator<Set> sets = ssoarOaiPmhEndpoint.listSets();

         sets.forEachRemaining(  x -> logger.info( x.getName() )  );
```

This will return the first 100 sets, but then I get an `IllegalStateException`:

```
java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
        at org.apache.http.util.Asserts.check(Asserts.java:34)
        at org.apache.http.impl.conn.BasicClientConnectionManager.getConnection(BasicClientConnectionManager.java:160)
        at org.apache.http.impl.conn.BasicClientConnectionManager$1.getConnection(BasicClientConnectionManager.java:142)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:423)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.lyncode.xoai.serviceprovider.client.HttpOAIClient.execute(HttpOAIClient.java:42)
        at com.lyncode.xoai.serviceprovider.handler.ListSetsHandler.nextIteration(ListSetsHandler.java:67)
        at com.lyncode.xoai.serviceprovider.lazy.ItemIterator.hasNext(ItemIterator.java:40)
        at com.example.XoaiTest.makeSimpleOaiPmhConnection(XoaiTest.java:58)
```

How do I resolve this issue?

**Comment by cgendreau** [comment]
See https://github.com/DSpace/xoai/pull/52
