### ISSUE TITLE
ServiceProvider.listRecords(..) throws NoSuchElementException

### ISSUE THREAD

**Issue by Abdull** [DSpace/xoai#57]
Provoking test case:

```
    @Test
    public void listRecords() throws NoSetHierarchyException, BadArgumentException, HttpException {
        OAIClient oaiClient = new HttpOAIClient("http://www.ssoar.info/OAIHandler/request");

         Context context = new Context()
                .withOAIClient(oaiClient)
                .withMetadataTransformer( "xoai", identity() );

         ServiceProvider ssoarOaiPmhEndpoint = new ServiceProvider(context);

         ListRecordsParameters parameters = new ListRecordsParameters();
         parameters.withMetadataPrefix("xoai");
         ssoarOaiPmhEndpoint.listRecords(parameters);
    }
```

Log (truncated to last lines. Notice that HTTPClient's `Wire` class does not output a full tag on the last line):

```
...
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,933]  << "[\r][\n]"
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,933]  << "1c4[\r][\n]"
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,933]  << "me="identifier">oai:gesis.izsoz.de:679</field>[\n]"
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,934]  << "        <field name="lastModifyDate">2012-08-29 23:40:31.76</field>[\n]"
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,934]  << "    </element>[\n]"
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,934]  << "    <element name="repository">[\n]"
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,934]  << "        <field name="name">SSOAR - Social Science Open Access Repository</field>[\n]"
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,934]  << "        <field name="mail">admin@ssoar.info</field>[\n]"
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,934]  << "    </element>[\n]"
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,934]  << "</metadata>[\n]"
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,935]  << "</metadata>[\n]"
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,935]  << "        </record>[\n]"
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,935]  << "        <record>[\n]"
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,935]  << "            <header>[\n]"
DEBUG [main o.a.http.wire o.a.h.i.c.Wire 2015-10-26 17:53:14,935]  << "                <identifier>oai:gesis.izsoz.de:1542</identifie"
```

Failure stacktrace:

``` java.util.NoSuchElementException
    at org.codehaus.stax2.ri.Stax2EventReaderImpl.throwEndOfInput(Stax2EventReaderImpl.java:453)
    at org.codehaus.stax2.ri.Stax2EventReaderImpl.nextEvent(Stax2EventReaderImpl.java:242)
    at com.lyncode.xml.XmlReader.next(XmlReader.java:134)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:42)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parseElement(MetadataParser.java:43)
    at org.dspace.xoai.serviceprovider.parsers.MetadataParser.parse(MetadataParser.java:34)
    at org.dspace.xoai.serviceprovider.parsers.RecordParser.parse(RecordParser.java:56)
    at org.dspace.xoai.serviceprovider.parsers.ListRecordsParser.next(ListRecordsParser.java:60)
    at org.dspace.xoai.serviceprovider.handler.ListRecordHandler.nextIteration(ListRecordHandler.java:70)
    at org.dspace.xoai.serviceprovider.lazy.ItemIterator.hasNext(ItemIterator.java:32)
    at org.dspace.xoai.serviceprovider.lazy.ItemIterator.<init>(ItemIterator.java:22)
    at org.dspace.xoai.serviceprovider.ServiceProvider.listRecords(ServiceProvider.java:57)
    at org.gesis.dda.harvester.harvesting.xoai.XoaiTest.listRecords(XoaiTest.java:94)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by Abdull** [comment]
@tdonohue, proof where this was completed.

**Comment by tdonohue** [comment]
@Abdull : This ticket relates to XOAI v4.x, which is not being maintained as noted in our README at https://github.com/DSpace/xoai#readme   Therefore it is unlikely to ever be fixed (which is why this ticket remained open for nearly 10 years before I've just closed it).  

As noted in that README, you may wish to consider using https://github.com/gdcc/xoai if you are interested in using XOAI v4.x

**Comment by Abdull** [comment]
@tdonohue, please "*Close as not planned*" or similar, but not "*Close as completed*". This will save users from incorrectly assuming that *this* issue is fixed in DSpace/xoai.
